CUWesternBlister/CommunityReviews

admin/activation.php
admin/deactivation.php
blister-community-reviews.php
functions.php

Merge pure SQL database prototype functionality for the 11/18/22 meeting with main.

Pure sql database

---

blister-community-reviews.php

Custom Post Prototypes

---

form_to_custom_post.php

In hindsight I could have included this in the other pull request because it was a really simple edit. I simply defined "post_excerpt" with the "user_html"  so excerpt swill only show height weight and ablility

Define excerpt branch

---

form_to_custom_post.php

The only changes I made were to the HTML in the "format_questions_answers_post_content" function. 
Instead of looping through the answers and questions, I changed the function and hardcoded the html and CSS style for the all the questions and answers.

This update is to style the post content html to look better.

---

admin/activation.php
admin/align_form_ids.php

Fills out the bcr_review_forms table with information from all fluent forms currently on the site and matches relevant form names to category ids.

Automatic form id alignment

---

admin/activation.php
admin/adminPage.php
admin/align_form_ids.php
admin/deactivation.php
admin/uploadInitialData.php
blister-community-reviews.php
functions.php
show_users_reviews.php
uninstall.php

Cleaned up the documents written by Gunnar. Should not affect functionality just removed or placed comments.

Clean code

---

form_to_custom_post.php

'question id in html, update to header qs and as with question ids, dynamic title for posts, empty open ended question handled'

Question id update

---

form_to_custom_post.php

Lukes suggested updates to the excerpt and review.

Review and excerpt update

---

admin/adminPage.php

Permissions now match the tech admin role on blister's site.

changed permissions required to view admin panel to Tech Admin

---

admin/activation.php
admin/deactivation.php
blister-community-reviews.php
form_to_custom_post.php
functions.php
generate_taxonomies.php
uninstall.php

sloppy fix to errors that Eric sent over. Removes table creation upon activation and table dropping upon deactivation. Also adds Backpack Review to the redirect list.

Wp databases error issues

---

admin/activation.php
admin/update_user_information.php
blister-community-reviews.php
community_reviews_custom_post.php
form_to_custom_post.php
generate_html.php
insert_custom_post.php
table_reading_functions.php
table_utils.php
table_writing_functions.php

split from to custom post into multiple files based on type/use of function, added all sanitization needed, made functions for parts of code that can be reused (getting question info, printing to test file), got rid of necessary code and comments.

Refactoring form to custom post

---

admin/deactivation.php
blister-community-reviews.php

Testing:
1. Pull this branch-> Deactivate -> Activate (make sure the plugin is version 1.3.1)
2. Write a few reviews (make sure they are identifiable as you will be checking for these in the database later)
3. Double Check to make sure your review was written to the database
4. Deactivate
5. Check to make sure the reviews you wrote are still in the database

Plugin no longer drops tables.

---

form_to_custom_post.php
generate_html.php
insert_custom_post.php
table_reading_functions.php

This should just need to test writing some reviews. To see if the metadata is correctly saved, should be able to use a filtering widget to sort by sport.

Updated Post Metadata Upon Submission

---

blister-community-reviews.php
fluent_form_functions.php
fluent_forms_functions.js
fluent_forms_scripts.php

Requires brand dropdown to have the name "1_1" and product dropdown to have the name "2"

Fluent forms auto populate brands and products

---

community_reviews_display_functions.php
widgets/community-reviews-display.php
widgets/community_reviews_display_widget_style.css
widgets/scripts.js

Testing requirements:
- The "Ski Boot Size" filter only appears when the category "Ski Boots" is selected on the widget
- Selecting different sizes on the "Ski Boot Size" filter correctly filters which Ski Boot reviews are shown

Ski boot size filter

---

community_reviews_display_functions.php
widgets/community-reviews-display.php
widgets/community_reviews_display_widget_style.css

Testing requirements:
- The keyword search text box appears in the filters on mobile and desktop
- Entering a word or phrase in the keyword field only shows the posts that contain that keyword

Filtering keyword search

---

widgets/community-reviews-display.php
widgets/community_reviews_display_widget_style.css
widgets/scripts.js

Testing requirements:
- Filters of filtering widget looks good at any width of the page

Filtering widget mobile fix

---

community_reviews_display_functions.php
fluent_form_functions.php
fluent_forms_functions.js

Testing Requirements:
- Brand and Product dropdowns on new fluent forms populate from database
- Brand dropdown selection filters options for Product dropdown on new fluent forms

Fixed conditional logic to match new fluent form ids

---

admin/adminAddToTable.php
admin/adminAddToTableAjax.php
admin/update_community_reviews_custom_posts.php
form_to_custom_post.php
generate_html.php
insert_custom_post.php

This allows the admin to add questions to forms and create new forms (when there is a tool to associate a new form with a category). Must follow the naming conventions for form fields outlined in the wiki documentation: [https://github.com/CUWesternBlister/CommunityReviews/wiki/New-Form-Creation-Admin-Input-Conventions](url)
To test, you must get the new ski review form from the page repo, or correct a form using the highlighted link above. 
Tests:
- Write a review and make sure the custom post creation is working with styling:
> Reviews to write:
- > Known brand and product
- > Known brand and unknown product
- > Unkown brand and product
- Make sure they appear in the BCR Flagged Reviews admin tool, and that you can approve and deny them. 
- Try making a question on an existing form …

Simplify form and custom post creation

---

admin/activation.php
admin/adminPage.php

does not run dbdelta to create table if table already exists

Fixing errors

---

admin/align_form_ids.php

Fixes duplicate entry bug on align_form_ids

Industry night version table bug fix
